### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by Djaler** [artemanufrij/hashit#2]
It would be nice if I'll be can select and copy resulting hash

**Comment by artemanufrij** [comment]
@Djaler could you test current master branch please?

![screenshot from 2017-08-17 00 54 48](https://user-images.githubusercontent.com/16517095/29388769-c91ce2a8-82e6-11e7-9013-3145126f70aa.png)

**Comment by greo-d** [comment]
In current version 0.1.3 which i recently installed from appcenter it's possible to copy the checksum with right-click. Great job and thanks for this little tool :)

**Comment by artemanufrij** [comment]
@J0Ar Thank you for your feedback. You are welcome :smile:
