### ISSUE TITLE
Context menu in File browser translatable?

### ISSUE THREAD

**Issue by greo-d** [artemanufrij/hashit#23]
I think the menu entry in file browser should be translatable...is this possible?
I did not find the string in .po-file and do not know how to add it :/

![screenshot von 2018-09-26 11 18 18](https://user-images.githubusercontent.com/23266409/46070367-e7460a80-c17d-11e8-864c-666542eadb39.png)

**Comment by artemanufrij** [comment]
@J0Ar good point. I will check it...

**Comment by artemanufrij** [comment]
just edit Name Field in following file:
```
[Contractor Entry]
Name=Show checksum
Name[de]=Checksumme ansehen
Icon=com.github.artemanufrij.hashit
Description=Shows checksum for a choosen file
Exec=com.github.artemanufrij.hashit %U
MimeType=!inode;
```
