### ISSUE TITLE
Contractor for all files

### ISSUE THREAD

**Issue by Djaler** [artemanufrij/hashit#4]
I think, you should changes MIME in contractor file so that users can check hash of all types of files.

**Comment by artemanufrij** [comment]
I'm not really sure, if it useful to change it for all files. Is it improved for .jpg, .bmp, .svg, .txt etc, etc.? I think no.

**Comment by Djaler** [comment]
For example, I need to verify checksum if I download some movie. Or archive, or big self-contained binary file

**Comment by artemanufrij** [comment]
Ok, thank makes sense
